### ISSUE TITLE
What's the difference 

### ISSUE THREAD

**Issue by bartlomiejmont** [KuzniaCo/browser-game#15]
export vs export default

**Comment by MackowiakMateusz** [comment]
When you use default export, you can export only one class from a file, because only one class can be default. When you use export, you can export many classes from a file, because any of them is not default.  Or so I think, I am not 100% sure.

It is also recommended to use export and not default export, because when you cahnge name of non-default export, references in another files also have changed names and it's easier to find what class you are looking for basing only on reference from another file, while searching for it in file with export.

It is nicely described here: https://stackoverflow.com/questions/33305954/typescript-export-vs-default-export(yep, I read that from here)
